"""Add user relationship to Donation

Revision ID: 1903825e889d
Revises: 3fe6eed14c5c
Create Date: 2025-11-21 15:43:59.883678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1903825e889d'
down_revision = '3fe6eed14c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True, comment='id пользователя'))
        batch_op.create_foreign_key('fk_donation_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donation_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
