"""First migration

Revision ID: d96484c6fbde
Revises: 
Create Date: 2025-11-15 15:51:01.531669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96484c6fbde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charityproject',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название проекта'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание проекта'),
    sa.Column('full_amount', sa.Integer(), nullable=False, comment='Целевая сумма проекта'),
    sa.Column('invested_amount', sa.Integer(), nullable=False, comment='Собранная на текущий момент сумма'),
    sa.Column('fully_invested', sa.Boolean(), nullable=False, comment='Флаг закрытия проекта'),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False, comment='Дата создания проекта'),
    sa.Column('close_date', sa.DateTime(timezone=True), nullable=False, comment='Дата закрытия проекта'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('donation',
    sa.Column('comment', sa.Text(), nullable=False, comment='Комментарий пользователя'),
    sa.Column('full_amount', sa.Integer(), nullable=False, comment='Сумма конкретного пожертвования'),
    sa.Column('invested_amount', sa.Integer(), nullable=False, comment='Собранная на текущий момент сумма'),
    sa.Column('fully_invested', sa.Boolean(), nullable=False, comment='Флаг закрытия проекта'),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False, comment='Дата создания проекта'),
    sa.Column('close_date', sa.DateTime(timezone=True), nullable=False, comment='Дата закрытия проекта'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation')
    op.drop_table('charityproject')
    # ### end Alembic commands ###
